[2024-09-25T09:26:15.520+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Batch_api_to_csv_with_dynamic_dates.fetch_paginated_api_data manual__2024-09-25T09:26:14.417722+00:00 [queued]>
[2024-09-25T09:26:15.524+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Batch_api_to_csv_with_dynamic_dates.fetch_paginated_api_data manual__2024-09-25T09:26:14.417722+00:00 [queued]>
[2024-09-25T09:26:15.524+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2024-09-25T09:26:15.531+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fetch_paginated_api_data> on 2024-09-25 09:26:14.417722+00:00
[2024-09-25T09:26:15.534+0000] {standard_task_runner.py:57} INFO - Started process 1084 to run task
[2024-09-25T09:26:15.536+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Batch_api_to_csv_with_dynamic_dates', 'fetch_paginated_api_data', 'manual__2024-09-25T09:26:14.417722+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/common_authentication_data_pipeline.py', '--cfg-path', '/tmp/tmpt03fzml1']
[2024-09-25T09:26:15.539+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask fetch_paginated_api_data
[2024-09-25T09:26:15.588+0000] {task_command.py:410} INFO - Running <TaskInstance: Batch_api_to_csv_with_dynamic_dates.fetch_paginated_api_data manual__2024-09-25T09:26:14.417722+00:00 [running]> on host fe5dec6acfed
[2024-09-25T09:26:15.832+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Batch_api_to_csv_with_dynamic_dates' AIRFLOW_CTX_TASK_ID='fetch_paginated_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T09:26:14.417722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T09:26:14.417722+00:00'
[2024-09-25T09:26:15.833+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/common_authentication_data_pipeline.py", line 45, in fetch_data_and_save
    current_time = datetime.now().astimezone("Asia/Bangkok")
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
[2024-09-25T09:26:15.837+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Batch_api_to_csv_with_dynamic_dates, task_id=fetch_paginated_api_data, execution_date=20240925T092614, start_date=20240925T092615, end_date=20240925T092615
[2024-09-25T09:26:15.842+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 41 for task fetch_paginated_api_data (tzinfo argument must be None or of a tzinfo subclass, not type 'str'; 1084)
[2024-09-25T09:26:15.852+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-09-25T09:26:15.862+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
